### ISSUE TITLE
FYI: monolitic timeline and sequencer

### ISSUE THREAD

**Issue by grammoboy2** [Stazed/non-timeline-xt#4]
Maybe interesting to know. The original author was thinking about to make timeline and sequencer monolithic, so it would be easier to sync and overview the audio and midi parts of a song. There where no concrete plans though and he didn't have a concrete idea how to do this without having to rewrite non-sequencer. 

I found non-sequencer always a fun pattern composing tool (all though it didn't received the same love as mixer and timeline did), so not sure if I agree with him here. Also not sure if there is much need for it nowadays, given how Ardour has evolved with the clip launcher. 

FYI

**Comment by Stazed** [comment]
I am not interested in this as I prefer the modular approach and I maintain seq32/seq42 for that purpose.
