### ISSUE TITLE
Fade-in always present at the beggining of a clip, even if explicitly disabled

### ISSUE THREAD

**Issue by domesya** [Stazed/non-timeline-xt#5]
Fade-in seems to always be present, even if explicitly disable fade-in. 
The result of that bug is that the transients of percussive sounds are weakened if they're at the beginning of a clip.

**Comment by Stazed** [comment]
Just pushed a change to the wip branch which disables declick on fade-in when the fade-in is disabled. Please test and let me know if this solves the issue.

**Comment by domesya** [comment]
Works as it should, the transients are preserved even if they're at the beginning of a clip.
Thanks for your work.
