### ISSUE TITLE
Hitting backspace with a menu open crashes the program.

### ISSUE THREAD

**Issue by M0JXD** [Stazed/non-timeline-xt#7]
Hi Stazed,

When this menu is open, pressing backspace crashes the program. This seems to be a carry over from Non again.

![right-click-xt-backspace-causes-crash](https://github.com/user-attachments/assets/271889e9-0df0-47b5-8be5-9839c73582ea)

I've also noticed the entry "Playhead to mouse" rarely works and should maybe be added to the other context menu for right-clicking on the waveform. I think the "P" shortcut should probably be mentioned in the manual too.

**Comment by Stazed** [comment]
> When this menu is open, pressing backspace crashes the program.

This is a long standing FLTK/NTK bug that happens with all popup menus. Occurs with every other FLTK program I tried.
https://www.fltk.org/str.php?L1356

Seems that no one tried it with backspace before now :-(.
Occurs when you move the mouse outside the popup and then hit backspace. 
Try filing a bug report with FLTK. In the mean time don't do that, use the arrow keys...

> I've also noticed the entry "Playhead to mouse" rarely works...

Could you open a separate issue for this and include information about your distro, desktop. I cannot re-produce it.

**Comment by M0JXD** [comment]
> In the mean time don't do that

Noted 😂 
I only found out by accident anyways, I meant to press enter. I'll file it with FLTK.

> Could you open a separate issue for this and include information about your distro, desktop. I cannot re-produce it.

Will do, I've just got a screen recording, I'll convert it to a gif and upload it in a new issue.

**Comment by M0JXD** [comment]
FYI: https://github.com/fltk/fltk/issues/1155#issue-2725325897

Edit: This issue is already fixed in the latest FLTK.
