### ISSUE TITLE
import-external-sources script can't handle spaces in file names

### ISSUE THREAD

**Issue by M0JXD** [Stazed/non-timeline-xt#9]
This is my terminal output, you can see it thinks the spaces mean different names/files:

![image](https://github.com/user-attachments/assets/63c7b78e-feb5-4381-a15a-b67f0b61718c)

I really appreciate the work you're doing on these audio projects. Is there any way I can support?

**Comment by Stazed** [comment]
Know anything about bash scripts? Fixing this would save me a lot of time as I rarely do them and would have to research this all over again.

**Comment by M0JXD** [comment]
Sure, I'll have a look 🙂
